### ISSUE TITLE
Add Twitter card (or similar) headers to base template

### ISSUE THREAD

**Issue by mojavelinux** [awestruct/awestruct.org#50]
Add Twitter card (or similar) headers to base template to facilitate page sharing.

**Comment by mojavelinux** [comment]
:+1:

**Comment by LightGuard** [comment]
As soon as the site goes live :)

On Tue, Feb 9, 2016 at 4:06 PM, Dan Allen <notifications@github.com> wrote:

> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct.org/issues/50#issuecomment-182126951>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by LightGuard** [comment]
That's all pushed.

On Tue, Feb 9, 2016 at 4:07 PM, Jason Porter <lightguard.jp@gmail.com>
wrote:

> As soon as the site goes live :)
>
> On Tue, Feb 9, 2016 at 4:06 PM, Dan Allen <notifications@github.com>
> wrote:
>
>> [image: :+1:]
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/awestruct/awestruct.org/issues/50#issuecomment-182126951>
>> .
>>
>
>
>
> --
> Jason Porter
> http://en.gravatar.com/lightguardjp
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp
