### ISSUE TITLE
getting_started and nokogiri 

### ISSUE THREAD

**Issue by richardfontana** [awestruct/awestruct.org#68]
Following the instructions at http://awestruct.org/getting_started/ I had trouble with getting nokogiri installed - I am running Fedora 22. Eventually I realized it was because I did not have libxml2-devel and libxslt-devel Fedora packages installed. Maybe the instructions should be revised to point out the need for those packages or their equivalents?

**Comment by LightGuard** [comment]
Thanks Richard, yes, would you care to make a pull request?

On Wed, Aug 26, 2015 at 3:49 PM, Richard Fontana <notifications@github.com>
wrote:

> Following the instructions at http://awestruct.org/getting_started/ I had
> trouble with getting nokogiri installed - I am running Fedora 22.
> Eventually I realized it was because I did not have libxml2-devel and
> libxslt-devel Fedora packages installed. Maybe the instructions should be
> revised to point out the need for those packages or their equivalents?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct.org/issues/68>.
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by richardfontana** [comment]
Actually now I see that the latest version of getting_started.adoc addresses this issue in "Install Package Dependencies on RPM Distributions", and the website must be still deploying an earlier version of the awestruct.org site.

**Comment by mojavelinux** [comment]
@LightGuard could you republish the website?

That reminds me that I still think we should move the site to gh-pages so that Travis can handle the update (and it's clear to everyone where the website lives).

**Comment by LightGuard** [comment]
There we go all updated. I'll look at tavis stuff later.

On Wed, Aug 26, 2015 at 8:09 PM, Dan Allen <notifications@github.com> wrote:

> @LightGuard <https://github.com/LightGuard> could you republish the
> website?
>
> That reminds me that I still think we should move the site to gh-pages so
> that Travis can handle the update (and it's clear to everyone where the
> website lives).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awestruct/awestruct.org/issues/68#issuecomment-135245266>
> .
>



-- 
Jason Porter
http://en.gravatar.com/lightguardjp

**Comment by mojavelinux** [comment]
:+1: Nice work!
