### ISSUE TITLE
Documentation about Ruby is inconsistent

### ISSUE THREAD

**Issue by derkork** [awestruct/awestruct.org#72]
The documentation about setting up Ruby is inconsistent. At the top it states that one should use Ruby 1.9.3 but then in the following sections there are instructions on how to install Ruby 2.3.0 (see http://awestruct.org/getting_started/). The article should be consistent.

**Comment by mojavelinux** [comment]
Would you like to do the honors of making the update?

See https://github.com/awestruct/awestruct.org/blob/master/getting_started.adoc
